In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

WARNING:tensorflow:From c:\ANNModel\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
model = load_model('model.h5')

WARNING:tensorflow:From c:\ANNModel\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [3]:
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

In [4]:
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo = pickle.load(file)

In [5]:
with open('sclaer.pkl','rb') as file:
    scaler = pickle.load(file)

In [6]:
##Example input data
input_data = {
    'CreditScore':600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance' : 60000,
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember': 1,
    'EstimatedSalary' : 50000
}

input_df = pd.DataFrame([input_data])

In [7]:
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()

c:\ANNModel\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [8]:
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [9]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [10]:
input_df = input_df.drop(columns=['Geography'])

In [11]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])

In [12]:
input_df = pd.concat([input_df.reset_index(drop=True), geo_encoded_df], axis=1)

In [13]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [14]:
input_scaled = scaler.transform(input_df)

In [15]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [16]:
prediction = model.predict(input_scaled)

1/1 [==============================] - 0s 95ms/step

In [17]:
prediction

array([[0.0368549]], dtype=float32)

In [19]:
prediction_proba = prediction[0][0]

In [20]:
if prediction_proba> 0.5:
    print('The customer is likely to Churn')
else:
    print('The customer is not likely to Churn')

The customer is not likely to Churn